### ISSUE TITLE
switching of the decimal maker not possible

### ISSUE THREAD

**Issue by hpvd** [burnpanck/MathJax-third-party-extensions#2]
One relatively important thing which seem not to work at the moment is the switching of the decimal maker to "," (comma)
from siunitx docu page 28
http://mirrors.ctan.org/macros/latex/contrib/siunitx/siunitx.pdf
the code for this should be
\num[output-decimal-marker = {,}]{1.23}
the demo shows still "." (dot) 

tested in live demo on 2015/10/28
http://codepen.io/pkra/pen/meLxzW

probably there should also be an (even more important) option to switch things like this globally...

**Comment by pkra** [comment]
I don't know siunitx but it sounds like a simple regex would do the trick, something like 

`this.GetBrackets(name,"").replace(/./,"{,}");`

**Comment by burnpanck** [comment]
I just pushed a fix for this one (which was so simple, I was surprised I did not implement that option right away). However, the current number interpreter is a regex-based reformatting of the input, which is then again forwarded to MathJax. This simple fix fails to produce proper spacing, since MathJax does not interpret the `,` as a decimal separator, and therefore inserts additional spacing after the comma. 
Note that starting from around line 200, all siunitx options are declared. A comment indicates if they are actually implemented.

**Comment by hpvd** [comment]
@burnpanck hey  - many thanks!!
so

> since MathJax does not interpret the , as a decimal separator, and therefore inserts additional spacing after the comma

=> this is a topic to work on in "general Mathjax"?
A `.` can also be used in both functions.

**Comment by pkra** [comment]
>  This simple fix fails to produce proper spacing, since MathJax does not interpret the , as a decimal separator, and therefore inserts additional spacing after the comma. 

That's TeX behavior, actually. Try my suggestion and output `{,}` to avoid the spacing.

**Comment by hpvd** [comment]
Thanks for your suggestion!

works like a charm:

http://codepen.io/pkra/pen/meLxzW
$$\num[output-decimal-marker = {,}]{1.23}$$
$$\num[output-decimal-marker = {{,}}]{1.23}$$
$$\num[output-decimal-marker = {.}]{1.23}$$

![2015-11-26_17h21_09](https://cloud.githubusercontent.com/assets/5681880/11427417/ffd66658-9462-11e5-9ea1-ebeeafe38880.png)

=> if this is that easy, coudn't this be easily done directly within this awesome extension?
So normal user could use original code without additional {}?

**Comment by pkra** [comment]
@hpvd since @burnpanck is just volunteering his time writing this, why not help him out and make a pull request?

**Comment by hpvd** [comment]
@pkra
I would like to, but I'm no developer only advanced user/reporter

**Comment by pkra** [comment]
@hpvd no worries. (But there's a first time for everything ;-))

**Comment by pkra** [comment]
@burnpanck you had a question in there that I missed -- sorry!

You need to make that `{,}` instead of `,` to get the spacing right.
