### ISSUE TITLE
please make available over cdn

### ISSUE THREAD

**Issue by hpvd** [burnpanck/MathJax-third-party-extensions#3]
Many thanks for all your awesome work!!
Would be perfect if to make this available also over math-jax cdn by integrating it in official 3rd party repository.

![2016-02-15_14h06_54](https://cloud.githubusercontent.com/assets/5681880/13049559/0d1518f8-d3ee-11e5-9141-5f4b2665fe43.png)

**Comment by burnpanck** [comment]
My next internal talk in the research group is approaching, time to review my web-based presentation framework, including MathJax... I issued  a PR to master.

**Comment by burnpanck** [comment]
Closing as the MathJax CDN doesn't exist anymore.
