### ISSUE TITLE
Dynamically defined Delimiters.

### ISSUE THREAD

**Issue by bd82** [burnpanck/MathJax-third-party-extensions#4]
Hello @burnpanck.

In [this post](https://github.com/pegjs/pegjs/issues/45#issuecomment-228655640)
You have mentioned a need for `globally configurable delimiters`.

I understood this to mean that the delimiters (for example commas in a list of items)
May be replaced/augmented with other kinds of delimiters (for example '_' or ".").

I am unable to assist with PEG.js. however I may be able to offer an alternative.
I have written a Javascript Parsing DSL called [**Chevrotain**](https://github.com/SAP/chevrotain).
You can [**try it online**](http://sap.github.io/chevrotain/playground/):
And have added an example showing [**dynamically defined Tokens**](https://github.com/SAP/chevrotain/tree/master/examples/parser/dynamic_tokens) (delimiters).

Other notable differences between Chevrotain and PEG.js.
- **NOT** a parse generator --> No Code Generation.
- Traditional two phase (Lexer + Parser) instead of a PEG parser.
- Automatic Error recovery / fault tolerance capabilities.

If this is relevant I'll be happy to receive any feedback. :)

**Comment by burnpanck** [comment]
Not an issue.
