### ISSUE TITLE
Example page no longer working?

### ISSUE THREAD

**Issue by chris2b5** [burnpanck/MathJax-third-party-extensions#5]
The example [here](http://rawgit.com/burnpanck/MathJax-third-party-extensions/add-siunitx-tex-extension/siunitx/sample-siunitx.html) seems no longer to be working?

Chrome says:
```
Uncaught ReferenceError: MathJax is not defined at sample-siunitx.html:174
```

**Comment by chris2b5** [comment]
I made a more minimal example that does work, but gives a warning that `siunitx.js` did not load correctly:

```
<!DOCTYPE html>
<html>
<head>
<title>MathJax siunitx MWE</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]]},
  errorSettings: {message: undefined},
    TeX: { extensions: ["[burnpanck]/siunitx/unpacked/siunitx.js"] }
  });
  MathJax.Ajax.config.path['burnpanck']  = 'https://rawgit.com/burnpanck/MathJax-third-party-extensions/master';
</script>
<script type="text/javascript" src="https://cdn.rawgit.com/mathjax/MathJax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML"></script>
    
</head>
<body>

<h2>Examples</h2>    

Trigger MathJax loading $!$.<br>

Testing basic MathJax: $\sqrt{a^2+b^2}$.<br>

Testing basic siunitx: $\SI{120}{\W\per\square\m}$. <br>

</body>
    
</html>
```

This gets everything from `rawgit`, not sure if those are the best URLs to use..?

**Comment by burnpanck** [comment]
Oh oh, that must be due to MathJax's recent closure of their CDN. Unfortunately, I didn't find the time to fix this. `rawgit` should be fine for the `siunitx` examples inside this repo, but for core MathJax, probably their recommended standard CDN should be used (which is now cdnjs.com): e.g. https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML

**Comment by chris2b5** [comment]
I could maybe take a little time to go through and change any references to core MathJax to point to cdnjs ...

It seems `cdnjs` haven't hosted `siunitx` or any of the [third party extensions](https://github.com/mathjax/MathJax-third-party-extensions) that used to be available through the MathJax CDN; I guess this means that, alongside retiring their CDN, MathJax are also bowing out of managing a collection of third party extensions?
If that's right, then it seems that:
* All third-party extension developers will need to request the various CDNs to carry their extensions individually - which is likely to lead to a much less 'tidy' structure than before
* Extensions will therefore need to be adopted to core MathJax if they are to be widely / easily accessible

I haven't really followed MathJax development, so I don't know what discussions there have been around this, or if there is already a different plan to handle the issue. 

Do you have any more information about how this is supposed to work from now on? Might it be possible to get `siunitx` added to core?

Also - any ideas about the warning?

**Comment by chris2b5** [comment]
OK, so I should probably have read this before posting that:
https://github.com/mathjax/MathJax-third-party-extensions/issues/39

* What would you like to do about this?
* Can I help..?

**Comment by pkra** [comment]
Given posts here and on the mathjax-3rd-party-extensions repo, you've worked things out. Let me know if you need more help.

The only problem in the sample from@chris2b5 above is that it is using `[burnpanck]` instead of `[Contrib]` -- which is the value hard coded at https://github.com/burnpanck/MathJax-third-party-extensions/blob/master/siunitx/unpacked/siunitx.js#L1332. (This hard-coding is a painful compromise from the early days of MathJax and will go away in v3.)

**Comment by burnpanck** [comment]
I have now finally followed the suggestion of the MathJax maintainers and created a new repository just for this extension: https://github.com/burnpanck/MathJax-siunitx. I did change the README and the examples to reflect the new location and lack of the MathJax CDN.

I have also created a pull request at CDNJS to include it there. However, I was unable to tick all the marks in their checklist, particularly regarding the popularity of this extension. I'm afraid at this point it might not get accepted. In that case, I propose to rely on rawgit (as the examples currently do).

With respect to your kind offer of help: Help is always appreciated! I unfortunately do not find much time currently to push this extension. There are still some holes that would need to be addressed. There is a file `ImplementationDetails` that highlights some of them.

**Comment by pkra** [comment]
Thanks for the update, Yves. I've updated the readme on the third party extensions repository.

I wouldn't worry about cdnjs (but I also think they don't care much about popularity these days as things are highly automated now).

But I think rawgit is just fine. People will also be able to use  gitcdn.xyz, raw.githack.com, and  jsdelivr (which now offers github based links, too).
